### ISSUE TITLE
inconsistent use of ularization in keywords

### ISSUE THREAD

**Issue by shguan10** [kaashmonee/scriptular#3]
Hello kind sir,

I would like to make an inquiry as to why certain keywords are not ularized. The most egregarious example of this is the bestow keyword, which is used at least once for every function to be written. Such an important keyword must follow one of the core tenets of this language, which is that the language uses the ularization as much as possible.

Might I make the humble request of renaming the bestow keyword to something more in line with the philosophy of this language, something like "bestowular"?

Good Day.

**Comment by kaashmonee** [comment]
Please modify the readme and issue a pull request. After you appropriately label the PR and assign me to it, I shall take a look. Thank you for your input.

**Comment by shguan10** [comment]
#4 I have done as you wished.

**Comment by shguan10** [comment]
Please note, good Sir, that I lack the necessary write permissions to this repo, and thus cannot assign anyone to a pull request on this repo.

**Comment by shguan10** [comment]
Closing, as this has been resolved. Thanks for accepting my PR
